"$schema" = 'https://starship.rs/config-schema.json'

[directory]
style = "bold blue"
truncation_length = 4

[directory.substitutions]
"Documents" = "DocumentsğŸ“„"
"Downloads" = "DownloadsğŸ’¾"
"Music" = "MusicğŸµ"
"Pictures" = "PicturesğŸ–¼ï¸"
"Videos" = "VideosğŸ“½ï¸"
"~" = "Home"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](yellow)"

[git_branch]
style = "cyan"
format = '[[$branch](fg:#769ff0 bg:#394260)]($style) '

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[nodejs]
symbol = "via [â¬¢ $version]($style) "

[erlang]
symbol = "â“” "

[pulumi]
symbol = "ğŸ§Š "